# Generated by Django 2.1.5 on 2019-02-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.IntegerField(blank=True, choices=[(1, '본관'), (2, '아단관'), (3, '현암관')], default=1),
        ),
    ]
