# Generated by Django 2.1.5 on 2019-02-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcms', '0002_auto_20190207_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationx', models.FloatField()),
                ('locationy', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('imformation', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
