# Generated by Django 2.1.5 on 2019-02-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcms', '0004_auto_20190209_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map_data',
            old_name='locationx',
            new_name='loc_x',
        ),
        migrations.RenameField(
            model_name='map_data',
            old_name='locationy',
            new_name='loc_y',
        ),
    ]
