# Generated by Django 2.1.5 on 2019-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcms', '0005_auto_20190209_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_data',
            name='loc_x',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='map_data',
            name='loc_y',
            field=models.CharField(max_length=200),
        ),
    ]
