# Generated by Django 2.1.5 on 2019-02-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcms', '0005_post_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.IntegerField(choices=[(1, '본관'), (2, '아단관'), (3, '현암관')], default=1),
        ),
    ]
